### ISSUE TITLE
Paste into Jupyter terminal?

### ISSUE THREAD

**Issue by sjobeek** [jupyter/notebook#104]
Is there any way to paste text into the Jupyter terminal?   

On chrome I'm able to copy from the terminal no problem, but can't figure out how to get text in.

The terminal is quite handy, but being unable to paste in snippets of text makes it difficult to execute larger commands.  I may just not have been able to figure out how to do it.

**Comment by rgbkrk** [comment]
I've noticed that I have to right click inside the little term js widget to get copy paste to work. That definitely needs a fix. Thanks for reporting it!

**Comment by takluyver** [comment]
See also chjj/term.js#37 and chjj/term.js#51.

**Comment by cboettig** [comment]
Looks like this has been resolved, yet I'm still not able to paste into the Jupyter terminal (in Ubuntu/Firefox).  I'm running jupyter via your current jupyter/datascience-notebook docker image, seems like it should be recent enough?  Any hints on debugging this?

**Comment by yuvipanda** [comment]
@cboettig I don't think this is in the current released version, is set to milestone 4.1 which hasn't been released yet.

**Comment by yuvipanda** [comment]
I can still repro this with the 4.1rc1 :(

**Comment by yuvipanda** [comment]
Can someone re-open this? This is still happening...

**Comment by minrk** [comment]
Some further clarification: The bug preventing paste in *all browsers* is fixed in notebook 4.1 (term.js 0.0.7). The bug preventing Firefox from pasting is apparently separate (chjj/term.js#51), and fixed in term.js master, but hasn't seen a release. There's nothing for us to do but wait for term.js 0.0.8.

**Comment by yuvipanda** [comment]
Actually, the fix hasn't been merged into master, and term.js development seems to have stopped :(

**Comment by aggFTW** [comment]
I'm not sure if this is a dumb question or not, but how are you getting pasting to work? `Ctrl+V` or `right click` don't work.

My Jupyter installation is:
```
The version of the notebook server is 4.2.0 and is running on:
Python 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
```

**Comment by takluyver** [comment]
@aggFTW Are you using Firefox? I think the fix for that is still not released.

**Comment by aggFTW** [comment]
I'm using Chrome.

**Comment by smokedsalmonbagel** [comment]
It sounds like this is working for some people.  For me, right clicking on the terminal does not show the paste option in Chrome Firefox or even IE.  Running Windows 7 on the client side and Jupyter version 4.1.0 on remote server.  The server is Ubuntu 14.04.
Is there a work around?

**Comment by mogthesprog** [comment]
Hey guys,

Just taken a look into this again as while it's not really a huge issue it is a a pain in the ass...  and then i foudn this:

https://github.com/sourcelair/xterm.js

A maintained fork of the unsupported term.js. Running a local instance myself and it seems like it solves this problem and a host of others, #1227 for instance.

Any chance we can get term.js swapped out for xterm.js? I have no idea how much work is entailed in doing this, so feel free to shout at me for asking you to move mountains...

Cheers

**Comment by takluyver** [comment]
@rgbkrk I think you were looking into this. Do you have a feel for how easy it would be to swap xterm.js in place of term.js?

**Comment by Carreau** [comment]
Fixed by #1591

**Comment by rahulremanan** [comment]
I can't  copy anything from the Jupyter terminal. I am using jupyter-client 5.2.0 and jupyter -core 4.4.0. Paste works fine, just can't copy anything from the terminal. Browsers tested: Chrome version 63, Firefox version 57 and Microsoft Edge. The xterm.js doesn't output anything to the clipboard when copying something from the jupyter console. Is there a fix for this issue?

**Comment by Yida147** [comment]
I can paste words by pressing **shift+insert** button

**Comment by felipeardilac** [comment]
You can paste text into the terminal doing shift+right click in the terminal and then select paste
