### ISSUE TITLE
Print events from matplotlib event handlers get swallowed

### ISSUE THREAD

**Issue by fperez** [jupyter/notebook#244]
Consider the following code in the notebook:
```python
%pylab notebook

fig, ax = plt.subplots()
ax.plot(np.random.rand(10))

def onclick(event):
    print ('button=%d, x=%d, y=%d, xdata=%f, ydata=%f'%(
        event.button, event.x, event.y, event.xdata, event.ydata))

cid = fig.canvas.mpl_connect('button_press_event', onclick)
```

these events never print anywhere.

The code does run, as can be seen by this code from @tacaswell: 

```python
%pylab notebook

fig, ax = plt.subplots()
ax.plot(np.random.rand(10))
collector = []
def onclick(event):
    collector.append('button=%d, x=%d, y=%d, xdata=%f, ydata=%f'%(
        event.button, event.x, event.y, event.xdata, event.ydata))

cid = fig.canvas.mpl_connect('button_press_event', onclick)
```

After clicking a couple of times:

```python
In [2]: collector
['button=1, x=201, y=275, xdata=2.196853, ydata=0.615071',
 'button=1, x=305, y=360, xdata=4.100549, ydata=0.770019',
 'button=1, x=421, y=223, xdata=6.205388, ydata=0.520279']
```

Somehow we're swallowing that stdout completely, I'm not 100% sure why right now. But to the user, it feels very puzzling. Given the equivalent code works just fine at the terminal, we should try to make it work without jumping through additional hoops in the notebook.

**Comment by takluyver** [comment]
I think it's another case of "where should the output go". The kernel is probably sending the output, but the notebook frontend doesn't know which cell to associate it with, so it discards it. I seem to recall @jdfreder spent some effort working round this for widgets. It would be good to have a more general solution, but I'm not sure what shape that would take.

**Comment by jdfreder** [comment]
Yeah, this is exactly the kind of thing I had to tackle with the widgets.  The notebook isn't smart enough to know what cell triggered the click event, so you need to tell it before sending the message to the backend.

Thanks for pinging me here @takluyver , this is one of the things I'm trying to reimagine with the output area work I'm doing.

**Comment by minrk** [comment]
Threaded output is associated with the most recent execution (by the kernel). With a GUI backend, I see the output in the cell (whichever is the most recently executed). With the nbagg backend, the most recent request is likely to be a comm message, and the nbagg backend is presumably dropping those messages. The nbagg backend could hook up the cell output callback for output messages it receives for its comms.

**Comment by fperez** [comment]
Mmmh... @ellisonbg, this is something that perhaps Ryan could work on as part of the MPL work.. . He might be able to make an improvement to the actual nbagg backend in MPL itself, working with @tacaswell (perhaps with some guidance from @minrk).

**Comment by tacaswell** [comment]
@blink1073 is also working on a widget based version of nbagg

**Comment by blink1073** [comment]
Yes, see #4582 for where I left off.

**Comment by blink1073** [comment]
The issue I ran in to originally that the div created by `mpl.show` was being changed from under its nose during `interact`.

**Comment by blink1073** [comment]
When the following cell is executed, the `comm_manager` creates an nbagg connection, which creates a div.   Might there be a way to add the nbagg div to the list of widgets in `interactive`?

```python
%matplotlib notebook
import matplotlib.pyplot as plt
from IPython.html.widgets import interactive

fig, ax = plt.subplots()
ax.plot(range(5))


vline = ax.axvline(1, color='k')
hline = ax.axhline(0.5, color='k')

def set_cursor(x, y):
    vline.set_xdata((x, x))
    hline.set_ydata((y, y))
    ax.figure.canvas.draw_idle()

interactive(set_cursor, x=ax.get_xlim(), y=ax.get_ylim())
```

**Comment by fperez** [comment]
@jdfreder, perhaps you have some insights that can help us here?

**Comment by jdfreder** [comment]
@blink1073 if you want the div to be treated as something that can be used by interact, you'll need to write a custom widget view and python widget.  The `value` traitlet of the widget will be what interact reads/writes.

**Comment by jdfreder** [comment]
If instead you want something that doesn't display in the widget area, you may be able to fool it by having a Python class that inherits from HasTraits, having a traitlet called `value`.  Interact would read/write that value like it was a widget.

**Comment by tacaswell** [comment]
Not sure this should be closed.  We also have an open mpl issue related to exceptions from event callbacks also being swallowed https://github.com/matplotlib/matplotlib/issues/5111

**Comment by ellisonbg** [comment]
OK, marking as 5.0

**Comment by tacaswell** [comment]
It could be argued that this should only be a bug on the mpl side, but I suspect that we will need some support from IPython on this one.

**Comment by blink1073** [comment]
Fixed by https://github.com/matplotlib/matplotlib/pull/5754.

<img width="839" alt="screen shot 2016-05-04 at 2 03 12 pm" src="https://cloud.githubusercontent.com/assets/2096628/15025868/04e64fac-1201-11e6-8dd6-2f3ffe105942.png">

**Comment by fperez** [comment]
Wonderful, thanks folks. Closing here (obviously users will need a newer mpl to get the fix, but that's fine).

**Comment by hakim89** [comment]
I would greatly appreciate a working example... in this code I can't even see the button

> %matplotlib notebook
> from matplotlib.widgets import Button
> import matplotlib.pyplot as plt
> def callback(event):
>     plt.text(event.xdata, event.ydata, 'clicked')
> 
> f,a = plt.subplots(1)
> b1 = Button(a,'Button1')
> b1.on_clicked(callback)
> plt.show()

**Comment by amnezzia** [comment]
the original example still does not work, I don't see any prints under the plot
ipython == 6.1.0
notebook == 5.0.0
matplotlib == 2.0.2

did recent changes revert the fix?

**Comment by tacaswell** [comment]
The changes referenced above were never released (it was targetted for 2.1) but in the mean time the widgets code has move through 3 major versions so the fixed nbagg did not work.  The upcoming 2.1 release (the first rc will be announced as soon as the mac wheels finish building on travis!) will still use the old js.

For a backend which is integrated with widgets see https://github.com/matplotlib/jupyter-matplotlib / ipympl

**Comment by mannyglover** [comment]
I used the example posted by @hakim89:

    %matplotlib notebook
    from matplotlib.widgets import Button
    import matplotlib.pyplot as plt
    def callback(event):
        plt.text(event.xdata, event.ydata, 'clicked')

    f,a = plt.subplots(1)
    b1 = Button(a,'Button1')
    b1.on_clicked(callback)
    plt.show()

It works as designed in my jupyter notebook: produces a big button, and whenever I click in the button, the word "click" is plotted on the button.  However, I wanted to test out if the std out would print out in the cell, so I added `print(event.xdata, event.ydata)` to the callback function.  Nothing prints out.  Then I tried ipympl per the link in @tacaswell's post above.  I did `pip3 install ipyml` and then changed `%matplotlib notebook` to `%matplotlib widget`.  Now, no plot is generated.

Versions of relevant packages are included in the screenshot below (from Jupyter Notebook -> Help -> About).  Also, matplotlib version is 2.2.2

<img width="293" alt="screen shot 2018-09-18 at 3 12 09 pm" src="https://user-images.githubusercontent.com/11902744/45710767-8d2dbf80-bb55-11e8-8fd5-ec7b360ea3b8.png">

**Comment by nvaytet** [comment]
If the print statements are for debugging purposes, you can use `os.write` instead:
```Py
import matplotlib.pyplot as plt
import os
fig, ax = plt.subplots()
ax.plot(np.random.rand(10))

def onclick(event):
    msg = 'button=%d, x=%d, y=%d, xdata=%f, ydata=%f\n'%(
        event.button, event.x, event.y, event.xdata, event.ydata)
    os.write(1, msg.encode())

cid = fig.canvas.mpl_connect('button_press_event', onclick)
```
The messages will show up in the terminal that is running the jupyter notebook.

**Comment by nvaytet** [comment]
This is still an issue for me. Using the example in the first message, I do not see any print statements anywhere in the notebook.
This is both for `%matplotlib notebook` and `%matplotlib widget` backends.

I would like to see this issue re-opened.

Versions (conda-forge):
- matplotlib: 3.3.2
- jupyter_client: 6.1.7
- jupyter_core: 4.6.3
- notebook: 6.1.5
- ipympl: 0.5.8

Thanks
