### ISSUE TITLE
404 GET error

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jupyter/notebook#2953]
I have:
python 3.6; jupyterlab 0.28.3; jupyter-nbextensions-configurator 0.2.8; ipython 6.2.1; ipywidgets 7.0.1

This is what I get when I launch `jupyter notebook`:

```
jupyter notebook
[I 21:55:58.313 NotebookApp] Loading IPython parallel extension
[I 21:55:58.354 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.8
[I 21:55:58.384 NotebookApp] JupyterLab alpha preview extension loaded from /Users/e/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 21:55:58.392 NotebookApp] Serving notebooks from local directory: /Users/e/Dropbox/devlib/notebooks
[I 21:55:58.392 NotebookApp] 0 active kernels
[I 21:55:58.392 NotebookApp] The Jupyter Notebook is running at:
[I 21:55:58.392 NotebookApp] http://localhost:8484/?token=ff4e7fc9d15c5a81949d5fec9bb32c3a32b49307dbb6ae2c
[I 21:55:58.392 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:55:58.394 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8484/?token=ff4e7fc9d15c5a81949d5fec9bb32c3a32b49307dbb6ae2c
[I 21:55:59.287 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 21:55:59.763 NotebookApp] 404 GET /static/components/moment/locale/en-gb.js?v=20171018215557 (::1) 10.01ms referer=http://localhost:8484/tree
```

I haven't found any new problem related to this, but it doesn't seem right.

How can I get rid of the `404` ?

**Comment by pavlin99th** [comment]
I had the exact same error on my Mac. Why did it request `en-gb` locale?
It turned out the code uses `navigator.language` property and in my chrome console it indeed showed `en-GB`. In my case I expected `en-US`.
So, if you are in US locale, not in UK, and on a Mac, the solution is: go to System Preferences -> Language & Region, there replace `English` with `English (U.S.)` in Preferred languages.
This solved the issue for me.

**Comment by chrisramsay** [comment]
@pavlin99th That's hardly a solution - what if you _are_ in the UK and do require `en-GB`?

**Comment by takluyver** [comment]
I think the error can safely be ignored, but #3051 should fix it.

**Comment by vellamike** [comment]
@takluyver I'm not sure this error can be ignored. My jupyter notebooks are taking ages to load since I started seeing this issue.

**Comment by takluyver** [comment]
I don't think that's directly related to this error, though you never know.

**Comment by takluyver** [comment]
This should be fixed now by #3048.

**Comment by vellamike** [comment]
I looked into it and you are right, it was a coincidence.

**Comment by vellamike** [comment]
@takluyver  you're right - it was just a coincidence.

**Comment by smartinsightsfromdata** [comment]
@takluyver FYI with `jupyter 1.0` & `notebook 5.2.2` (most recent versions in `pypi`) the problem remains.  Have I missed something?

```
[W 14:41:38.928 NotebookApp] 404 GET /static/components/moment/locale/en-gb.js?v=20171202144128 (::1) 45.74ms referer=http://localhost:8484/tree
```

**Comment by takluyver** [comment]
The change hasn't been released yet. If you look at #3048, the 'milestone' on the right is set to 5.3.
