### ISSUE TITLE
PDF download: nbconvert failed: '/path/to/benchmarks.ipynb' exists but is not a directory

### ISSUE THREAD

**Issue by olalonde** [jupyter/notebook#2987]
When clicking `Download As > PDF`, I'm getting the following 500 error:

```
nbconvert failed: '/path/to/benchmarks.ipynb' exists but is not a directory
```

**Comment by gnestor** [comment]
This was just fixed by https://github.com/jupyter/notebook/pull/2981 which will be included in a 5.2.1 release today.

**Comment by HaoyangFan** [comment]
Do you know how to check the version of jupyter notebook and how to upgrade it?

**Comment by gnestor** [comment]
```bash
jupyter notebook --version
# to upgrade to notebook 5.2.1rc1
pip install notebook --upgrade --pre
```

**Comment by HaoyangFan** [comment]
So 5.2.1 is not a official release for now?
Whenever I try
`pip install notebook --upgrade && jupyter notebook --version`
The version turns out to be still 5.2.0, which does not fix the nbconvert issue

**Comment by takluyver** [comment]
Yup, `rc1` means it's a pre-release, so you need the `--pre` flag to get it. I think @gnestor is planning to release 5.2.1 very soon.

**Comment by HaoyangFan** [comment]
thanks

**Comment by joshuacook** [comment]
Until https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile gets rebuilt this `Dockerfile` will run the update:

```
FROM jupyter/scipy-notebook
RUN conda update --yes notebook
```

From the same directory:

```
$ docker build -t updated_scipy_nb .
```

**Comment by gnestor** [comment]
Thanks @joshuacook!! 👍
