### ISSUE TITLE
Notebook 5.2.x produces sprintf error when trying to open a Notebook

### ISSUE THREAD

**Issue by rwmajor2** [jupyter/notebook#3235]
We have a sandbox environment for sample Notebooks and when we try to open an existing sample (http://notebooks.esri.com/notebooks/samples/03_org_administrators/move_existing_user_content_to_a_new_user.ipynb), it generates the following error:

![image](https://user-images.githubusercontent.com/3799165/35109803-617abcfa-fc45-11e7-99c5-6b5e07302a5e.png)

It appears to be having a problem parsing parts of the Notebook file.  However, we do not experience this issue when working with Notebook 5.0.x.

Web browser console reports the following:

![image](https://user-images.githubusercontent.com/3799165/35109926-a9b48442-fc45-11e7-8b88-64008fd5a7ea.png)

```javascript
 /**
     * Success callback for loading a notebook from the server.
     * 
     * Load notebook data from the JSON response.
     * 
     * @param {object} data JSON representation of a notebook
     */
    Notebook.prototype.load_notebook_success = function (data) {
        var failed, msg;
        try {
            this.fromJSON(data);
        } catch (e) {
            failed = e;
            console.error("Notebook failed to load from JSON:", e);
        }
```

Any thoughts?

**Comment by takluyver** [comment]
It looks like the error is coming from the translation machinery (Jed). I think it's trying to produce a warning and that's going wrong. Are you willing to share a copy of the notebook that causes the problem?

**Comment by takluyver** [comment]
#3236 should fix this.

To work around it in the meantime, replace `null` with `1` (or any integer) on line 101.

**Comment by rwmajor2** [comment]
@takluyver Man, I am having a tough time manually applying this fix.  If I  edit the file on my local Windows PC (C:\Anaconda3\Lib\site-packages\notebook\static\notebook\js\outputarea.js) and then start jupyter notebook, the JS still has the old value in Developer Tools (error still presents itself):

```javascript
    OutputArea.output_prompt_classical = function(prompt_value) {
        return $('<bdi>').text(i18n.msg.sprintf(i18n.msg._('Out[%d]:'),prompt_value));
    };
```

Where do I need to edit this file so it "sticks"?  I have cleared my browser and done everything I can think of.

Below is what my JS file on disk now looks like:
```javascript
   OutputArea.output_prompt_classical = function(prompt_value) {
        return $('<bdi>').text(i18n.msg.sprintf(i18n.msg._('Out[%s]:'),prompt_value));
    };
```

**Comment by rwmajor2** [comment]
@takluyver Disregard last post.  I forgot my JS 201 basic lesson of needing to edit the main.min.js file.

**Comment by takluyver** [comment]
Yeah,  it's either editing the minified file or [rebuilding the javascript](http://jupyter-notebook.readthedocs.io/en/stable/contributing.html#setting-up-a-development-environment).

**Comment by S4lem** [comment]
Hi, I had the same error and thanks to @takluyver I worked around by giving arbitrary values to the different execution_count parameters in the file.

**Comment by Zohaggie** [comment]
@takluyver I am also getting this, and even after just now doing conda upgrade jupyter. I am on windows 10. Unfortunately it's worse than just an annoying message, the notebook is truncated, and goes from 1.212 kb to 75 kb. Was the fix dependent upon opening the notebook in jupyter?

**Comment by takluyver** [comment]
If you're not using the latest version of the notebook (currently 5.7.0), upgrade using `pip install --upgrade notebook` or `conda install notebook` (best to use whichever tool was already responsible for installing it).

**Comment by rwmajor2** [comment]
@takluyver did this fix not show up until 5.7?

**Comment by takluyver** [comment]
It should have been fixed in 5.5, but someone on #4065 describing a similar error was still using 5.2.2. My first suspicion is that anyone still experiencing it needs to upgrade.

**Comment by pushpendrapratap** [comment]
upgrading jupyter notebook to 5.7 version fixed this issue for me
