### ISSUE TITLE
KeyError: 'loop'

### ISSUE THREAD

**Issue by ReneKat** [jupyter/notebook#3499]
Hello,
I am new to programming so I appreciate your help. I am running jupyter for the first time on my computer and have already run into a snag. The first time it ran no issues, 8 hours later I started to get the below error, followed by a whole bunch of subsequent errors. I was hoping to get some guidance as to how and solve this error.
I am running OSX 10.13.3 High Sierra
Python 3.6
Thank you,
RenéKat

```
[E 21:16:23.441 NotebookApp] Uncaught exception POST /api/sessions (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/Users/Owl/miniconda3/envs/prog4biol/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
        value = obj._trait_values[self.name]
    KeyError: 'loop'
```

**Comment by ReneKat** [comment]
This is the traitlets.py
```
def get(self, obj, cls=None):
        try:
            value = obj._trait_values[self.name]
        except KeyError:
            # Check for a dynamic initializer.
            dynamic_default = self._dynamic_default_callable(obj)
            if dynamic_default is None:
                raise TraitError("No default value found for %s trait of %r"
                                 % (self.name, obj))
            value = self._validate(obj, dynamic_default())
            obj._trait_values[self.name] = value
            return value
        except Exception:
            # This should never be reached.
            raise TraitError('Unexpected error in TraitType: '
                             'default value not set properly')
        else:
return value
```

**Comment by isingh3** [comment]
I am having the same issue after I updated the "dask" and immediately got the same error.

**Comment by takluyver** [comment]
Is it possible that something else got updated along with dask?

@minrk any ideas how dask could affect...whatever this is? :confused:

**Comment by isingh3** [comment]
Probably yes, because initially, I had a totally different issue while working with Pandas and Tensorflow. Trying to solve the said problem I came to this page (link below) and saw the "dask update" which caused me to run into this immediately.

https://github.com/tflearn/tflearn/issues/766

For now, I fixed kernel problem by quickly uninstalling Anaconda and reinstalling it. I know that is not a solution but I had a deadline.

**Comment by minrk** [comment]
It's peculiar that it would only log the last stack frame. Then we can't even know what object encountered the error.

The output of `conda list` would be helpful for tracking down what version the error might be in. My *guess* is that it's an issue in an outdated package and ensuring you have the latest version of jupyter-client, pyzmq, notebook you won't see this error. It's possible that installing/upgrading dask could have resulted in downgrading/upgrading something else (dask.distributed also uses tornado, so that could be relevant).

It's also possible that there's still a bug somewhere in a little-used corner of the codebase.

**Comment by ReneKat** [comment]
Hello there,
What fixed my error was similar to what @minrk is suggesting. The issue stemmed from an out of date version of condo or jupyter (not sure exactly which one.). Initially I did uninstall/reinstall but my problem persisted. 
This is what worked for me:
# Update Condo 
`conda update -n root -c main conda`
## I rearranged my channels in condo config to have default listed first:
`conda config --remove channels bioconda
conda config --remove channels conda-forge
conda config --append channels bioconda
conda config --append channels conda-forge
`
#Then I updated condo (again?) and jupyter
`conda update conda
conda update jupyter
jupyter notebook`

Hope that helps if you encounter the problem again. 
Best,
RenéKat

**Comment by pgenevski** [comment]
I got this error after installing the toree kernel. Managed to fix it by running
`pip install jupyter -U`

I guess the toree installation updated some of the dependencies to an incompatible version.

**Comment by takluyver** [comment]
Closing this as it seems to have been a dependency mismatch of some kind. You can still comment if you want to add more details, and we can reopen it if there's something to be fixed in Jupyter.

**Comment by makmanalp** [comment]
Same happened to me, the dependency is  `jupyter-client-5.2.3`. I think toree overspecifies the version it needs.

**Comment by sweeney-th** [comment]
I Installed toree on my Debian system, it broke both of my kernals (Scala, Python3).

Uninstalling Torre via pip did nothing. Updating jupyter (a la  pgenevski) yields no change.

Trying to install  jupyter-client-5.2.3 using pip and sudo both produce error stating it can't find a version that satisfies requirement . 

Briefly ran as root for and Python3 kernal works, Scala is gone. 

Is there anything else I can try?

**Comment by sweeney-th** [comment]
fixed: 

As part of recommended install/reinstall procedure, Jupyter recommends upgrading pip. pip3 v10 currently breaks it's Debian command:

https://stackoverflow.com/questions/49836676/python-pip3-cannot-import-name-main-error-after-upgrading-pip

https://github.com/pypa/pip/issues/5221

Solved by un-installing and reinstalling pip3 then updating Jupyter.
