### ISSUE TITLE
Is there a way to jump to the last executed cell?

### ISSUE THREAD

**Issue by matanox** [jupyter/notebook#3844]
It would be extremely helpful, when writing code simultaneously to running parts of long notebooks, as well as to jump to the cell that failed in a long sequence of cells!

**Comment by noklam** [comment]
interested in this as well, is there a state keep track of the current selected cell/last selected cell so we can jumping between the two?

**Comment by DataInformer** [comment]
Jumping to the cell that failed in a long sequence indeed seems extremely useful!  Maybe this could be accomplished by autoscrolling as cells are run?  (then when they stop running, you'd be on the cell with an error)

**Comment by noklam** [comment]
@DataInformer I have implemented an notebook extension for this.  You can install the master branch of it since they stopped to release new pip version for a year. https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/go_to_current_running_cell/README.md

**Comment by voloddia** [comment]
@noklam It seems that your extension only jumps to a cell only if it's still running?

**Comment by noklam** [comment]
@voloddia yes, it only work for running cell.

**Comment by FarisHijazi** [comment]
here's some javascript that does the job, someone please put this in an extension or @noklam please add it to yours, as usually we want the last run cell even if it's not running.  
NOTE: this doesn't work if cells were cleared

A quick hack is to put this in a bookmarklet: drag the code to the bookmarks bar (or create a new bookmark with the code as the location) and now you have a button that takes you to the latest cell.

```javascript
javascript:(function(){
  var cellCounters = document.querySelectorAll("#notebook-container > div > div.input > div.prompt_container > div.prompt.input_prompt");
  
  var numbers = [].map.call(cellCounters, a=> parseInt(a.innerText.match(/\[(.+)\]/)[1].replace(" ", '-1')));
  
  var maxIndex = numbers.indexOf(Math.max(...numbers));
  
  var lastCell = cellCounters[maxIndex];
  
  lastCell.scrollIntoViewIfNeeded();
})();
```

**Comment by qkum** [comment]
> here's some javascript that does the job, someone please put this in an extension or @noklam please add it to yours, as usually we want the last run cell even if it's not running. NOTE: this doesn't work if cells were cleared
> 
> A quick hack is to put this in a bookmarklet: drag the code to the bookmarks bar (or create a new bookmark with the code as the location) and now you have a button that takes you to the latest cell.
> 
> ```js
> javascript:(function(){
>   var cellCounters = document.querySelectorAll("#notebook-container > div > div.input > div.prompt_container > div.prompt.input_prompt");
>   
>   var numbers = [].map.call(cellCounters, a=> parseInt(a.innerText.match(/\[(.+)\]/)[1].replace("*", '999999999999999999').replace(" ", '-1')));
>   
>   var maxIndex = numbers.indexOf(Math.max(...numbers));
>   
>   var lastCell = cellCounters[maxIndex];
>   
>   lastCell.scrollIntoViewIfNeeded();
> })();
> ```

i know nothing about coding in java. but it says there is an error in the code linked. and adding an '(' or '{' does not fix it.

**Comment by noklam** [comment]
Happy to accept any PR if someone want to make it work, unfortunately the repository is not maintain actively it may take some time to get it merged.
