### ISSUE TITLE
Running | Notebooks | Shutdown buttons not working, fix found

### ISSUE THREAD

**Issue by chrislnorth** [jupyter/notebook#4865]
I found that if i change this code in static/tree/js/main.min.js:

            .click(function() {
                var path = $(this).parent().parent().parent().data('path');
                that.shutdown_notebook(path);
            })

to:

            .click(function() {
                var path = $(this).parent().parent().parent().parent().data('path');
                that.shutdown_notebook(path);
            })

then the Shutdown buttons work.  Needs one more .parent() link in the chain.

jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 6.0.0
qtconsole        : 4.5.4
ipython          : 5.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.1
jupyter lab      : 1.0.2
nbconvert        : 5.5.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.2

MacOS 10.13.6
Safari 12.1.12

Hope that helps.

**Comment by slumbi** [comment]
Confirm, it works for me too

**Comment by fboerman** [comment]
I can confirm to have the same problem

**Comment by MBlistein** [comment]
Me too

**Comment by MBlistein** [comment]
I can confirm both problem and fix, thanks for that!

**Comment by paxtonfitzpatrick** [comment]
Can also confirm both problem and fix! Thanks @chrislnorth!

`jupyter --version`:
```
jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.3
jupyter lab      : 1.1.4
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.2
```
Also,
```
macOS 10.14.5
Chrome 76.0.3809.132 (Official Build) (64-bit)
```

**Comment by rgbkrk** [comment]
Filed https://github.com/jupyter/notebook/pull/4939 as a fix.

**Comment by istavnit** [comment]
> I found that if i change this code in static/tree/js/main.min.js:
> 
> ```
>         .click(function() {
>             var path = $(this).parent().parent().parent().data('path');
>             that.shutdown_notebook(path);
>         })
> ```
> 
> to:
> 
> ```
>         .click(function() {
>             var path = $(this).parent().parent().parent().parent().data('path');
>             that.shutdown_notebook(path);
>         })
> ```
> 
> then the Shutdown buttons work. Needs one more .parent() link in the chain.
> 
> jupyter --version
> jupyter core : 4.5.0
> jupyter-notebook : 6.0.0
> qtconsole : 4.5.4
> ipython : 5.8.0
> ipykernel : 5.1.2
> jupyter client : 5.3.1
> jupyter lab : 1.0.2
> nbconvert : 5.5.0
> ipywidgets : 7.5.1
> nbformat : 4.4.0
> traitlets : 4.3.2
> 
> MacOS 10.13.6
> Safari 12.1.12
> 
> Hope that helps.

In which folder this static/tree folder can be found on windows?

**Comment by lrlthink** [comment]
> I found that if i change this code in static/tree/js/main.min.js:
> 
> ```
>         .click(function() {
>             var path = $(this).parent().parent().parent().data('path');
>             that.shutdown_notebook(path);
>         })
> ```
> 
> to:
> 
> ```
>         .click(function() {
>             var path = $(this).parent().parent().parent().parent().data('path');
>             that.shutdown_notebook(path);
>         })
> ```
> 
> then the Shutdown buttons work. Needs one more .parent() link in the chain.
> 
> jupyter --version
> jupyter core : 4.5.0
> jupyter-notebook : 6.0.0
> qtconsole : 4.5.4
> ipython : 5.8.0
> ipykernel : 5.1.2
> jupyter client : 5.3.1
> jupyter lab : 1.0.2
> nbconvert : 5.5.0
> ipywidgets : 7.5.1
> nbformat : 4.4.0
> traitlets : 4.3.2
> 
> MacOS 10.13.6
> Safari 12.1.12
> 
> Hope that helps.

How to fix this bug after install by conda install?

**Comment by fboerman** [comment]
It has already been fixed in a new release. upgrade your notebook version to the latest

**Comment by istavnit** [comment]
What is a root folder of the "Static"
Thank you,

Igor Stavnitser
Tel: 773.841.7645

**Comment by XonFire** [comment]
It works thank you so much!!
just search for static/tree/js/main.min.js in your Anaconda3 folder and edit it with notepad

**Comment by TomLin** [comment]
> It has already been fixed in a new release. upgrade your notebook version to the latest

Actually I tried to reinstall the package using `pip install -U jupyter`, but the bug still exists. I could only fix the problem by manually modifying the code in static/tree/js/main.min.js as instructed by @chrislnorth.

**Comment by DennisvdPluijm** [comment]
> > It has already been fixed in a new release. upgrade your notebook version to the latest
> 
> Actually I tried to reinstall the package using `pip install -U jupyter`, but the bug still exists. I could only fix the problem by manually modifying the code in static/tree/js/main.min.js as instructed by @chrislnorth.

Are you sure you have the latest version? I just upgraded from 6.0.0 to 6.1.0, the bug has been fixed in the latest version.
[note: for Anaconda I had to use conda-forge, otherwise it wouldn't update to 6.1.0]

**Comment by nealmcb** [comment]
@TomLin I had to `pip install -U notebook` to get the upgrade to 6.1.1.

FWIW, I was also confused by the variety of package versions reported by `jupyter --version`, and the fact that it reports a version there for `jupyter-notebook`, but there is no package by that name in pypi.

```
$ jupyter --version
jupyter core     : 4.6.1
jupyter-notebook : 6.1.1
...

**Comment by kevin-bates** [comment]
@nealmcb - thanks for providing the upgrade tip.

Regarding the `jupyter` command, this doesn't produce a list of packages, but rather a list of _commands_ and their respective versions.  It resides in the `jupyter_core` package.  For the `--version` argument, it essentially [walks a well-known list of jupyter packages](https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/command.py#L195-L216) and produces their version information prefixed by the corresponding command.

Since you thought these were packages, others probably do as well.  It might make for a helpful contribution to include the package name in this output or allow for another option to `--version` which produces this information.  Since there may be scripts consuming this output, something like `jupyter --packages`, that produces the same output but with package names, might be helpful.  At any rate, this would be something to take up in [`jupyter_core`](https://github.com/jupyter/jupyter_core) if you (or anyone else) is interested.
