### ISSUE TITLE
Can't open jupyter lab with cmd

### ISSUE THREAD

**Issue by Kushal1507** [jupyter/notebook#5609]
I was trying to open jupyter lab with cmd with the command jupyter lab and so it gave me an error
`Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Roaming\Python\Python37\Scripts\jupyter.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\jupyter_core\command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\jupyter_core\command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-lab` not found.
`

**Comment by kevin-bates** [comment]
The `jupyter` command essentially takes its first argument (e.g., `lab`) and composes a command (e.g., `jupyter-lab`) in which it looks for.  The location of the command is typically the `bin` directory of the current python env (`sys.prefix`) although on Windows I believe this is the adjacent `scripts` folder (not sure about the case).

Given that it can't find `jupyter-lab`, I would check to make sure you have `jupyterlab` installed in this python env.  If so, you might ensure that the appropriate `scripts` folder is included in your `PATH`.

**Comment by Kushal1507** [comment]
@kevin-bates  thanks for the answer the jupyter lab is fixed but now there's another problem 
`Traceback (most recent call last):
  File "D:\Extra Apps,Softwares\Anaconda3\lib\site-packages\jupyterlab_server\server.py", line 14, in <module>
    from notebook.base.handlers import (
  File "C:\Users\KUSHAL\AppData\Roaming\Python\Python37\site-packages\notebook\base\handlers.py", line 22, in <module>
    from tornado import web, gen, escape, httputil
  File "C:\Users\KUSHAL\AppData\Roaming\Python\Python37\site-packages\tornado\web.py", line 87, in <module>
    from tornado.httpserver import HTTPServer
  File "C:\Users\KUSHAL\AppData\Roaming\Python\Python37\site-packages\tornado\httpserver.py", line 29, in <module>
    import ssl
  File "D:\Extra Apps,Softwares\Anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Extra Apps,Softwares\Anaconda3\Scripts\jupyter-lab-script.py", line 5, in <module>
    from jupyterlab.labapp import main
  File "D:\Extra Apps,Softwares\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 14, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "D:\Extra Apps,Softwares\Anaconda3\lib\site-packages\jupyterlab_server\__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "D:\Extra Apps,Softwares\Anaconda3\lib\site-packages\jupyterlab_server\app.py", line 9, in <module>
    from .server import ServerApp
  File "D:\Extra Apps,Softwares\Anaconda3\lib\site-packages\jupyterlab_server\server.py", line 26, in <module>
    from jupyter_server.base.handlers import (                          # noqa
ModuleNotFoundError: No module named 'jupyter_server'`

**Comment by kevin-bates** [comment]
Looks like lab's attempt to determine between running against notebook or jupyter_server got side-tracked due to a tornado import issue.  (It should not be trying to load jupyter_server right now unless you're running the 3.0 alpha release [I think].)

I recommend ensuring your installation of tornado is fairly up to date (>= 6.0).  Should the problem persist, this may require some help from lab folks.

cc: @blink1073

**Comment by blink1073** [comment]
Yes, the original import failure causing the second.  It sounds like you may need to reinstall anaconda @Kushal1507 if there is a DLL error.  You can try opening an issue on https://github.com/ContinuumIO/anaconda-issues.

**Comment by Zsailer** [comment]
@Kushal1507, closing this issue since it appears to be outdated. 

Feel free to reopen if you're still having issues.
