### ISSUE TITLE
Restoring computation output after disconnect in Notebook

### ISSUE THREAD

**Issue by hadim** [jupyter/notebook#641]
Following this discussion https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jupyter/8hyGKoBY6O0/RyEDDyOZAQAJ, I'd like to open an issue to track down progress on this feature.

The idea would be to add the capability to restore output of a running kernel after client reconnection.

Feel free to ask me to move this issue in a more appropriate jupyter project if needed.

**Comment by rshpeley** [comment]
Hey Carreau. I noticed on the google forum you said the code would need a significant refactor, and MinRK said it involved storing outputs on the server. In my case I'm ok with losing the outputs during the disconnect. I just need to be able to reconnect the browser session to the kernel to get new outputs and to get at the data and code I've loaded. Kernel/Reconnect doesn't do it. I've also tried closing the tab and opening a new one from the Jupyter base page.

This is fairly important for me. I live in a rural area with a poor internet connection and my notebook takes about 8 hours to load. I'm pretty well guaranteed to have an interruption during that time.

**Comment by rshpeley** [comment]
Still looking into this. This is currently just a problem for me on Jupyter, but I'm more interested in getting it solved for JupyterHub. I'm planning to use it to instruct a class at the university and students losing access to their assignment work through a disrupted connection is not an option.

[mosh](https://mosh.org/) have solved this problem on terminals and it seems to me that using mosh's SSP  (State Synchronization Protocol) with Speculation adapted to Jupyter Notebook requirements would be the best solution to this problem (see the [mosh paper](https://mosh.org/mosh-paper.pdf)).

If you want to hand this problem off to JupyterHub that's ok with me, but others may like to see a solution for Jupyter as well.

**Comment by minrk** [comment]
This isn't really a JupyterHub problem. It should be fixed in the notebook (specifically JupyterLab), hopefully before too long.

**Comment by post2web** [comment]
This feature would be great!

**Comment by manuelsh** [comment]
Loosing the output of a jupyter notebook if you are not connected to the hosting computer is quite annoying.

**Comment by a-rodin** [comment]
Just a side note: [Apache Zeppelin notebook](https://zeppelin.apache.org/) doesn't have this problem as it stores all the outputs on the server side, so the interruptions or multiple connects are handled in it transparently.

**Comment by louismartin** [comment]
Is there any update on this issue?

**Comment by jasongrout** [comment]
Not beyond the discussion and issues linked above, that I know of.

There is (slow, contributors welcome!) work going on in JupyterLab around real-time collaboration, which also involves moving notebook state to the server, which solves this issue. @rgbkrk, @captainsafia and others have also experimented with moving state to the server in the nteract project. And @williamstein's cocalc implementation of a notebook frontend *does* have this feature - it saves state on the server, so you can reconnect whenever you want and get the full state.

So there have been some initial experiments (jlab, jupyter_server, nteract), and at least one full implementation tied to a platform (cocalc).

**Comment by cossio** [comment]
Any news on this? Is there an issue / PR that one can check to track progress on this?

**Comment by rgbkrk** [comment]
Follow this repository for the related effort: https://github.com/jupyterlab/rtc

**Comment by apophenist** [comment]
Hi friends,

I have this problem often, when the output buffer stops (I use Atom/Hydrogen), and I lose visibility of long running processes. 

I have found a bit of a workaround which may be helpful to others (but it requires this to be done upfront, i.e. there is no way that I have found to resume output from existing processes.

The solution requires SSH access, and involves redirecting [logging](https://stackoverflow.com/questions/41507783/writing-scikit-learn-verbose-log-into-an-external-file) to a file as follows:
```
    import sys
    log_file = 'results.log'
    sys.stdout=(open(log_file,"w"))
    print ("Simulation for {}".format(column_to_cycle))
    clf = RandomizedSearchCV(RandomForestRegressor(random_state = 0), param_distributions = param_grid, n_iter = 200, cv=3, random_state = 42, verbose = 51, n_jobs=8)
    clf.fit(X_train.iloc[:,2:], y_train.iloc[:,0])
    sys.stdout.close()
```

However, buffering in std.out proved to be an issue, so [this post's answer](https://stackoverflow.com/questions/107705/disable-output-buffering) proved helpful in overriding this:

```
class Unbuffered(object):
   def __init__(self, stream):
       self.stream = stream
   def write(self, data):
       self.stream.write(data)
       self.stream.flush()
   def writelines(self, datas):
       self.stream.writelines(datas)
       self.stream.flush()
   def __getattr__(self, attr):
       return getattr(self.stream, attr) 0.9928668713004366

```

and replace above sys.stdout=(open(log_file,"w")) with:     
`sys.stdout=Unbuffered(open(log_file,"w"))`

Now, you can ssh into the machine, `run docker exec -it image_name bash` and `tail -f` the log file.

Hope this helps, it seems to be the best solution for now.

**Comment by banderlog** [comment]
Just met this issue with losing 5h computations on GPU. Used AI notebook in GCP. Thought that it will do plots with a closed browser, but I thought wrong :(

**Comment by astrojuanlu** [comment]
> There is (slow, contributors welcome!) work going on in JupyterLab around real-time collaboration, which also involves moving notebook state to the server, which solves this issue.

To my understanding, Real Time Collaboration is now supported in JupyterLab https://github.com/jupyterlab/jupyterlab/issues/5382 

@jasongrout as I read in https://blog.jupyter.org/how-we-made-jupyter-notebooks-collaborative-with-yjs-b8dff6a9d8af

> Currently, we still send HTTP PUT requests to save a document to the file system via the Jupyter Server. Once we have the Yjs CRDT working in Python, we will create a Python implementation of the shared notebook model which will allow the Jupyter Server to directly access the collaborative state and synchronize that with the file system.

It is not clear to me if the notebook state is now handled by the server and therefore this issue is fixed, or if it is still present.

**Comment by jasongrout** [comment]
> To my understanding, Real Time Collaboration is now supported in JupyterLab [jupyterlab/jupyterlab#5382](https://github.com/jupyterlab/jupyterlab/issues/5382)

This will be released in the upcoming 3.1 release, behind a command-line flag.



> It is not clear to me if the notebook state is now handled by the server and therefore this issue is fixed, or if it is still present.

This is still present for now, but the infrastructure needed to move things to the server is being put in place by the RTC work. Moving state to the server is another big project that builds on the RTC work being done now.

**Comment by cossio** [comment]
What issue / repo / PR should one follow to get relevant updates on this issue? Will it be resolved on this repo or on jupyterlab?

**Comment by tgpfeiffer** [comment]
Related to https://github.com/jupyter/notebook/issues/641#issuecomment-872469554: I have tried the Jupyter collaboration feature in the latest release (3.3.3) and I found out that if user A starts a long-running computation, then the output is synced across browsers to all collaborators and they can see it in real-time, reload their browser windows etc., but if A does it, then we are back at the place of this issue, the output goes into the void and cannot be accessed later.

So as written by @jasongrout above this still seems to be a WIP. I'd be interested to contribute some work here, where is it happening? Any main issue, meetings etc. where this feature is driven forwards?

**Comment by Wh1isper** [comment]
> Related to [#641 (comment)](https://github.com/jupyter/notebook/issues/641#issuecomment-872469554): I have tried the Jupyter collaboration feature in the latest release (3.3.3) and I found out that if user A starts a long-running computation, then the output is synced across browsers to all collaborators and they can see it in real-time, reload their browser windows etc., but if A does it, then we are back at the place of this issue, the output goes into the void and cannot be accessed later.
> 
> So as written by @jasongrout above this still seems to be a WIP. I'd be interested to contribute some work here, where is it happening? Any main issue, meetings etc. where this feature is driven forwards?

I am also interested in this issue, which is a problem of the overall Jupyter architecture. Jupyter puts all file-related operations on the front end, which disappears after closing the tab page, naturally leading to the problem of missing output

Looking at the behavior of JupyterLab, I found that JupyterLab itself has some problems with the kernel state loop. For example, when reconnecting to a kernel that is performing a computation task, JupyterLab will lose the ability to track its output, such as the following code.

```python
import time 
while True:
  time.sleep()1
  print(1)
```

I think the reconnection problem should be solved first, and the loss of output during front-end shutdown is probably tolerable.

Second, the best solution is to leave the output of the computation task to the backend and return it to the frontend appropriately.

**Comment by jasongrout** [comment]
> I am also interested in this issue, which is a problem of the overall Jupyter architecture.

There is active work in JupyterLab to correct this architecture issue. This builds on work done over the last year in real-time collaboration. @davidbrochart, is there a top-level issue in JupyterLab tracking the work to move state to the server side?

**Comment by jasongrout** [comment]
It looks like https://github.com/jupyterlab/jupyterlab/issues/11434 contains useful discussion about the current state of the RTC work, and https://github.com/jupyterlab/jupyterlab/issues/2833 (also noted above) is another good issue to follow.

**Comment by davidbrochart** [comment]
Besides the issues @jasongrout mentioned, https://github.com/jupyterlab/jupyterlab/pull/12360 is the PR that will probably solve this issue. I am actively working on it, and it also depends on the development of https://github.com/y-crdt/ypy. Give us one more month or so!

**Comment by cossio** [comment]
Now that https://github.com/jupyterlab/jupyterlab/pull/12360 is merged, any updates on this issue? Thanks!

**Comment by davidbrochart** [comment]
Seems to work:
https://user-images.githubusercontent.com/4711805/168849750-7a1a3a29-807f-457e-b9cc-471afa30960c.mp4

**Comment by davidbrochart** [comment]
But it already works with Jupyter 3.4.2, so this is not related to https://github.com/jupyterlab/jupyterlab/pull/12360.

**Comment by cossio** [comment]
@davidbrochart Wowwww had no idea! So if I just upgrade to latest Jupyterlab I will get this fix?

**Comment by davidbrochart** [comment]
Could you post a screencast?

**Comment by cossio** [comment]
Maybe. If I try to refresh the notebook browser window (hit F5), however, I lose all output :disappointed:

**Comment by davidbrochart** [comment]
Ah, but that's another issue. You might want to continue the discussion in https://github.com/jupyterlab/jupyterlab/issues/12455.

**Comment by williamstein** [comment]
> Maybe. If I try to refresh the notebook browser window (hit F5), however, I lose all output 😞

IIRC @rgbkrk  (?) told me he added a hack long ago to Jupyter so that it would save up and push  out messages that were missed when the user's network connection is down temporarily.  As you note, it was just a small hack, and doesn't work when you refresh your browser. Maybe @rgbkrk has further thoughts...

**Comment by davidbrochart** [comment]
But the long-term fix is to move all kernel management (low-level kernel protocol) from the front-end to the back-end. In the end JupyterLab would merely be a (live) document viewer, and wouldn't talk to kernels directly.

**Comment by Wh1isper** [comment]
> Screencast.from.17-05-22.18_25_55.mp4 
> @davidbrochart I tried to replicate your video, with Python. Notice here that the outputs keep coming in even after the Throttling setting is set to Offline, so I'm not sure this is a good experiment?

This is probably because Google Chrome's dev tool does not disconnect websockets that are already connected

**Comment by Kesanov** [comment]
This issue is my biggest pain with jupyter **by far**.
However, judging by the progress made since 2015, 
it looks like this won't get _ever_ implemented
despite this being probably the most upvoted issue here -.-

Since it seems upvotes fail as means of motivation,
would it be possible to put a bounty on this issue
(where people could donate small amount of money
as easily as hitting the upvote button)
that would be paid to the person who fixes it?

**Comment by astrojuanlu** [comment]
The current status of this issue is a bit unclear to me. gh-12360 was merged, which in theory addressed it at least partially, but then there's also gh-12455, which "would probably need a complete rework of JupyterLab's architecture". Additionally, some videos were posted in the latest comments but as @Wh1isper points out, they were using Chrome Dev Tools and therefore are not representative.

Would the devs add some clarification here? i.e. what changed after gh-12360 and what remains.

**Comment by davidbrochart** [comment]
- https://github.com/jupyterlab/jupyterlab/pull/12360 doesn't address this issue.
- https://github.com/jupyter-server/jupyverse/pull/191 is a step in that direction, but it's very experimental.

**Comment by Wh1isper** [comment]
I found a discussion here that in this [issue](https://github.com/jupyter/notebook/issues/1647#issuecomment-377166130), the cache of the notebook does not work because the browser loses the previous msg_id after refreshing, so I propose here that jupyterlab should store the `msg_id` in ipynb to ensure message recovery after refreshing

here is my issue https://github.com/jupyterlab/jupyterlab/issues/12455

**Comment by Wh1isper** [comment]
JupyterLab 4.0 already has the ability to push file changes from local to the front end, and I'm trying to write a plugin that executes cell code and writes to files

https://github.com/Wh1isper/jupyter_kernel_executor

**Comment by TDVPHD** [comment]
I came across this problem not so long ago and I went to stackoverflow. Eventually I figured out that there was not straight-forward to solve this problem. So I went with a run-around instead. I saved all the values that I wanted in a file, which I then open in another notebook on the same IP. From there, I can open, plot, and display summaries without disturbing the measurement/calculation notebook. 

Wanted to post here in case this would be a suggestion for others who are seeking an answer to this question

**Comment by drf5n** [comment]
If you know you are going to lose the connection, you can capture the output for use later:

```
%%capture CELLOUT
for i in range(5):
    print(i)
    time.sleep(5)
```

next cell:
```
print(CELLOUT.stdout)
```

**Comment by quangbilly79** [comment]
It's freaking 2026. Has this crucial feature been added to JupyterLab/JupyterNotebook yet?

**Comment by williamstein** [comment]
> It's freaking 2026. Has this crucial feature been added to JupyterLab/JupyterNotebook yet?

In 2006 when I wrote the first ever web notebook (the early "Sage Notebook") I very clearly remember going home one weekend planning to figure out how to solve this problem, and thinking "Nobody would use a web notebook without this being solved."  Boy was I wrong!    :-)

**Comment by kuraga** [comment]
Nobody should have created _computations on client_! In any year. And @marimo-team, too.

**Comment by davidbrochart** [comment]
Well, we have [server-side execution](https://jupyterlab-realtime-collaboration.readthedocs.io/en/latest/configuration.html#storage-configuration) if you enable real-time collaboration, that solves this issue. That works with [jupyverse](https://github.com/jupyter-server/jupyverse) and it seems that it could be [supported in jupyter-server](https://github.com/jupyter-server/jupyter_server/pull/1570) soon.
