### ISSUE TITLE
In virtual environment wrong version of python is used

### ISSUE THREAD

**Issue by eudaiman** [jupyter/notebook#7583]
## Description
In my virtual environment I installed jupyter notebook. But when I tried running it, I discovered that it's using the wrong python.

## Reproduce
Create venv. Then install venv jupyter: 
python -m pip install jupyter
python -m ipykernel install --name=my-kernel-name --prefix=$VIRTUAL_ENV
Then in jupyter notebook import sys and print sys.version. I warrant you it will not be the one in venv.

## Expected behavior
Should be the same version as python -V in terminal.

## Context

Using Ubuntu 20.04, everything else is latest version (python, jupyter etc.)

**Comment by prajwal-38** [comment]
The issue arises because the --prefix=$VIRTUAL_ENV flag for ipykernel install is incorrect. It installs the kernel in the wrong location, not properly linking it to the virtual environment's Python.

create your venv and then activate it, and while in venv you need to install jupyter and ipykernel using pip

`pip install jupyter ipykernel
`

and then install kernel properly

`python -m ipykernel install --user --name=my-kernel-name --display-name "Python(venv)"
`

Hope this helps

**Comment by RRosio** [comment]
Hi @eudaiman, I hope the suggestions above were helpful and that you were able to resolve your issue! Since this doesn’t appear to be an error within the Notebook codebase, I’ll go ahead and close this. However, please feel free to open a new issue if you run into any other problems that should be addressed in this repository.

**Comment by jkteske** [comment]
@RRosio, I am having this same issue now. When I follow your instructions and open Jupyter notebook within my venv, it still shows that the server is starting from the base application directory:

```
python -m ipykernel install --user --name=igrins-plp-env --display-name "Python(venv)"
Installed kernelspec igrins-plp-env in /Users/jteske/Library/Jupyter/kernels/igrins-plp-env
```

```
(igrins-plp-env)  jupyter notebook
JupyterLab extension loaded from /opt/anaconda3/lib/python3.9/site-packages/jupyterlab
JupyterLab application directory is /opt/anaconda3/share/jupyter/lab
```

Do you have any other advice? Thanks!
